name: Testing

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Spoof the AWS config files
      run: |
        mv  ./src/config/awsConfig.sample.ts  ./src/config/awsConfig.ts
        mv  ./src/config/config/userManagerConfig.sample.ts  ./src/config/userManagerConfig.ts 
        mv  ./src/config/config/attributeConfig.sample.ts  ./src/config/attributeConfig.ts 

    - name: Clear JS dependencies cache
      run: yarn cache clean

    - name: Install project dependencies
      run: yarn install

    - name: Run frontend linter
      run: yarn lint:quiet

    - name: Generate coverage reports
      run: yarn test:coverage

    - name: Run static code analyser on frontend
      run: yarn analyse

    - name: fix code coverage paths
      working-directory: ./var/reports
      run: |
        sed -i 's/\/home\/runner\/work\/spicy-hamster\/spicy-hamster\//\/github\/workspace\//g' phpunit.xml
        sed -i 's/\/home\/runner\/work\/spicy-hamster\/spicy-hamster\//\/github\/workspace\//g' phpunit.coverage.xml
        sed -i 's/\/home\/runner\/work\/spicy-hamster\/spicy-hamster\//\/github\/workspace\//g' lcov.info

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}